### ISSUE TITLE
setup of CI 

### ISSUE THREAD

**Issue by jarekratajski** [neeffect/nee#1]

**Comment by krasnoludkolo** [comment]
Will travis be enought for now?

**Comment by pivovarit** [comment]
Travis is becoming obsolete after GitHub Actions went live.

It's more reliable, faster, and easier to configure.

An example from one of my projects: https://github.com/pivovarit/parallel-collectors/blob/master/.github/workflows/build.yml

**Comment by jarekratajski** [comment]
I had good experiences with Travis but I vote to try this GitHub Actions. 
(but anything is better than nothing)

**Comment by krasnoludkolo** [comment]
Yep, lets use GH Actions

**Comment by jarekratajski** [comment]
done (simply, dirty, but works)
